version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

# This file is used by AWS Elastic Beanstalk.  
# Use docker-compose-dev.yml for local dev builds.